
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[347] =
    {   0,
       62,   62,   66,   64,   63,   62,   50,   64,   64,   56,
       49,   64,   44,   45,   54,   53,   41,   52,   48,   55,
       23,   23,   42,   38,   57,   43,   58,   61,   20,   20,
       46,   47,   59,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   39,   60,   40,   51,    0,    0,   63,
       63,   62,   37,    0,    0,   28,    0,    0,    0,   40,
       32,    0,    0,    0,    0,   29,   30,   31,   26,    0,
        1,   27,   22,    0,   23,    0,   23,   47,   39,   46,
       34,   36,   35,   20,    0,    0,   20,   20,   20,    9,
       20,   20,   20,   14,   20,   20,   20,   20,   20,   33,

       28,    0,    0,    1,    0,   24,   24,    0,    0,    1,
        0,   26,    0,    0,    0,    0,    1,    1,    1,   26,
        0,   27,   22,    0,   25,   21,   20,   20,   20,   20,
       20,   20,   13,   15,   20,   20,   20,   20,    0,    0,
       28,    0,    0,    0,    1,    1,    1,    1,    1,    0,
        0,    0,   24,    0,    0,    0,    1,    1,    1,    1,
        1,    0,   26,    0,    0,    2,    0,    1,    1,    1,
        1,    1,    0,   26,    0,   27,   25,   21,   20,    6,
       20,   20,   20,   11,   20,   20,   20,   18,   20,   28,
        0,    0,    0,    2,    0,    1,    1,    1,    1,    1,

        1,    1,    0,   24,    0,    0,    0,    2,    0,    1,
        1,    1,    1,    1,    1,    1,    0,    2,    0,    0,
        2,    1,    1,    1,    1,    0,   26,    5,    7,   20,
       20,   12,   20,   20,   19,    0,    2,    0,    0,   28,
        2,    0,    1,    1,    1,    1,    0,    0,    2,    0,
        0,   24,    2,    0,    1,    1,    1,    1,    1,    1,
       20,   10,   16,   17,    1,    1,    1,    1,    0,    1,
        1,    1,    1,   20,    0,    8,    0,    0,    0,    0,
        4,    0,    0,    0,    0,    0,    1,    0,    1,    3,
        0,    4,    0,    0,    1,    1,    1,    1,    0,    0,

        0,    0,    1,    1,    1,    1,    0,    2,    0,    1,
        1,    1,    1,    1,    1,    0,    2,    0,    1,    3,
        1,    1,    1,    1,    1,    0,    4,    2,    1,    1,
        1,    1,    0,    2,    0,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   30,    1,   38,   39,   40,   41,

       42,   43,   30,   44,   45,   30,   46,   47,   30,   48,
       49,   30,   30,   50,   51,   52,   53,   54,   55,   33,
       30,   56,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[382] =
    {   0,
        0,    0,  917,  889,   59,   62,   49,   65,   51,   54,
       66,   71,  882,  869,  868,   62,  862,   69,   72,   75,
       90,  127,   77,  853,   93,   79,   80,  852,  163,   72,
      844,  841,  838,  803,   71,  801,  797,   77,   82,  788,
      783,  778,  782,  805,   81,  804,  793,  792,  115,  132,
      138,  149,  791,  113,  121,  790,  154,  146,  120,  789,
      786,  217,  119,  218,  158,  785,  773,  772,  214,  160,
      152,  220,  251,  258,  228,  287,  314,  771,  766,  757,
      754,  750,  746,    0,  219,  255,  717,  708,  697,  691,
      689,  683,  677,    0,  673,  670,  633,  641,  628,  651,

     1194,  660,  282,  283,  144,  629, 1194,  640,  284,  334,
      335,  616,  345,  618,  347,  359,  612,  361,  153,  293,
      362,  593,  339,  167,  365,  356,  566,  548,   61,  553,
      542,  543,    0,    0,  527,  537,  537,  516,  387,  360,
      386,  407,  408,  388,  412,  543,  421,  432,  223,  182,
      441,  406,  445,  452,  461,  465,  463,  533,  472,  481,
      281,  179,  482,  237,  490,  290,  492,  501,  325,  509,
      515,  517,  518,  529,  413,  521,  503,  513,  469,    0,
      454,  443,  439,    0,  417,  411,  397,    0,  398,  423,
      536,  307,  540,  556,  564,  570,  583,  584,  582,  603,

      604,  590,   52,  404,  602,  394,  622,  623,  641,  642,
      643,  661,  610,  662,  680,  611,  410, 1194,  681,  389,
      682,  688,  689,  700,  439,  537,  690,    0,    0,  350,
      317,    0,  293,  296,    0,  699,  274,  717,  559,  711,
      725,  723,  736,  744,  745,  763,  206,  743,  256,  764,
      513,  752,  782,  770,  783,  784,  802,  803,  811,  822,
      270,    0,    0,    0,  828,  829,  830,  836,  411,  842,
      848,  854,  855,  250,  644,    0,  664,  431,  205,  454,
      471,  698,  350,  856,  624,  872,  870,  879,  866, 1194,
      890,  892,  896,  909,  474,  491,  910,  888,  908,  916,

      917,  933,  499,  934,  925,  663,  942,  926,  950,  951,
      959,  967,  968,  976,  984,  975,  978,  992,  995,  251,
      986, 1003, 1006, 1009, 1012, 1020, 1026, 1037, 1039, 1043,
     1045, 1041, 1057, 1059, 1061, 1063, 1065, 1082, 1074, 1088,
     1090, 1099, 1101, 1107, 1110, 1194,  243, 1135, 1137, 1139,
     1141, 1143,  187, 1145, 1147, 1149, 1151, 1153, 1155, 1157,
     1159, 1161, 1163, 1165, 1167, 1169, 1171, 1173, 1175,  178,
      176, 1177,  174, 1179,   85, 1181, 1183, 1185, 1187, 1189,
     1191
    } ;

static const flex_int16_t yy_def[382] =
    {   0,
      346,    1,  346,  347,  347,  346,  347,  348,  347,  347,
      347,  349,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,   29,
      347,  347,  347,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,  347,  347,  347,  347,  347,  347,  347,
      346,  346,  347,  348,  350,  347,  348,  348,  347,  347,
      347,  349,  351,  349,  349,  347,  347,  347,  347,  352,
      353,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,   29,  348,  349,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,  347,

      346,  350,  354,  355,  347,  347,  346,  351,  356,  357,
      347,  347,  352,  358,  352,  352,  353,  359,  353,  347,
      347,  347,  347,  347,  347,   76,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,  354,  360,
      352,  354,  354,  354,  355,  353,  361,  355,  355,  347,
      356,  362,  352,  356,  356,  356,  357,  353,  363,  357,
      357,  347,  347,  358,  352,  347,  364,  359,  353,  359,
      359,  359,  347,  347,  347,  347,  347,  347,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,  358,
      360,  360,  354,  348,  365,  361,  355,  361,  359,  361,

      361,  361,  347,  358,  362,  362,  356,  349,  366,  363,
      357,  363,  359,  363,  363,  363,  358,  346,  352,  358,
      352,  367,  359,  359,  353,  347,  347,   29,   29,   29,
       29,   29,   29,   29,   29,  360,  350,  354,  360,  352,
      354,  354,  368,  361,  361,  355,  347,  362,  351,  356,
      362,  352,  356,  356,  369,  363,  363,  357,  359,  359,
       29,   29,   29,   29,  361,  359,  361,  361,  347,  363,
      359,  363,  363,   29,  347,   29,  347,  370,  371,  370,
      370,  370,  371,  371,  371,  372,  373,  374,  375,  346,
      372,  372,  372,  372,  373,  373,  376,  373,  374,  374,

      374,  374,  375,  377,  375,  375,  372,  370,  378,  376,
      373,  376,  376,  376,  376,  374,  371,  379,  377,  358,
      375,  377,  377,  377,  377,  372,  372,  372,  380,  376,
      376,  373,  374,  374,  374,  381,  377,  377,  375,  376,
      376,  376,  377,  377,  377,    0,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346
    } ;

static const flex_int16_t yy_nxt[1255] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       30,   29,   29,   31,    4,   32,   33,   29,   34,   35,
       36,   37,   38,   29,   39,   29,   29,   29,   29,   40,
       41,   29,   29,   42,   43,   29,   44,   45,   46,   47,
       50,   51,   50,   51,   52,   51,   49,   55,   49,   49,
       56,   49,   53,   63,   61,   66,   49,   85,   60,   49,
       48,   86,   57,   49,   67,  303,   49,   70,   64,   49,
       69,   69,   71,   68,   49,   59,   49,   49,   49,   58,

       79,   78,   82,   83,  247,   65,   72,   49,   73,   73,
       49,  181,  182,   80,   88,   55,   81,   74,   56,   89,
       75,   75,   76,   92,   94,   93,  101,   70,  107,   95,
       57,   74,   71,   50,   51,   50,   75,   49,  100,   51,
       51,   51,   75,   72,   49,   77,   77,   58,  346,   49,
       51,   52,   51,  108,   74,  102,   55,   75,   75,   56,
      346,   49,  114,   57,  118,  118,  103,  105,   74,  119,
      119,  104,  115,   75,  295,   64,  283,  116,  280,   75,
       49,   84,   84,  150,   49,  125,  125,  117,   58,   84,
       84,   84,   84,   84,   84,   84,   49,  163,  163,   49,

       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   63,
       63,   55,  284,   49,   56,  346,  106,  106,  203,  285,
      109,   49,   69,   69,   64,  110,   57,   49,  120,  120,
      197,  111,  112,   48,  112,   49,  269,  121,  122,  217,
      122,   65,   65,   58,  218,  111,  112,   63,   75,   75,
      112,  121,  122,  164,   48,  107,  122,   72,   49,   73,
       73,  124,   64,  124,   75,   49,  125,  125,   74,  101,
       75,  123,  123,  346,  140,   55,  152,  141,  146,   65,
      108,  276,   74,  153,  142,  147,  154,  123,  211,  143,

      148,  155,   70,  123,   49,  126,  126,   71,  102,  114,
       49,  120,  120,  126,  126,  126,  144,  149,  156,  191,
      173,  174,  274,  174,  126,  126,  126,  126,  126,  126,
       72,   49,   77,   77,  173,  174,   63,  118,  264,  174,
      263,   74,  119,  158,   75,   75,  159,  114,  162,  114,
      162,  160,   49,  163,  163,   74,   49,  115,  262,  165,
       75,  114,  116,  114,  166,  190,   75,  284,  161,  123,
      123,  167,  191,  171,  285,  175,  168,  175,  172,   49,
      176,  176,   49,  125,  125,  123,  178,  178,  114,  140,
      114,  123,  141,  177,  192,  177,  114,  261,  115,  142,

      142,  164,  178,  116,  143,  143,  205,  177,  178,  140,
      140,  177,  141,  141,   55,  204,  164,  146,  205,  193,
      195,  144,  217,  140,  194,  196,  199,  346,   49,  197,
       49,  176,  176,  200,   55,  164,  281,  146,  201,  235,
      206,  144,  144,  152,  147,  234,  149,  114,  282,  148,
      153,  118,  275,  154,  152,  202,  119,  115,  155,  281,
      233,  153,  116,  152,  207,   63,  149,  114,  232,  208,
      153,  282,  158,  209,  152,  156,  281,  154,  210,  296,
      211,  213,  155,   63,  214,  231,  156,  230,  282,  215,
      158,  311,  114,  159,  220,  156,  296,  161,  160,   49,

      163,  163,  165,  114,  115,  229,  216,   49,  311,  221,
      112,  114,  112,  222,  228,  161,  321,  114,  223,  114,
       49,  171,  204,  306,  112,  205,  172,  224,  112,  222,
       49,  226,  225,  226,  223,   49,  227,  227,   49,  176,
      176,  190,  140,  178,  178,  141,   49,  206,  236,  122,
      169,  122,  193,  237,   49,  227,  227,   57,   55,  178,
      169,   56,  189,  122,  190,  178,  239,  122,  103,  240,
      192,  191,  140,  104,  144,  199,  142,  188,  187,  186,
      185,  241,  243,  184,  114,   55,  140,  244,  146,  199,
       58,  183,  114,  192,  171,  147,  200,  180,  242,  172,

      148,  201,  200,  179,  202,  140,  140,  201,  199,  199,
       49,  204,  114,  114,  248,  245,  243,  149,  202,  249,
      246,  244,  171,  214,  152,   63,  290,  172,  215,  169,
      164,  153,  106,   49,  207,  109,  206,  202,  202,   64,
      110,  284,  346,  251,  152,   63,   49,  277,  285,  278,
      252,  213,  158,  154,  255,  159,  156,   65,  253,  256,
      160,   49,  346,  152,  152,  290,  279,  277,   49,  278,
      213,  213,  138,  214,  257,  254,  216,  161,  215,  258,
      321,   49,  152,  114,  114,  137,  279,  306,  136,  213,
      220,  114,  255,  115,  167,  216,  216,  256,  116,  168,

      171,  222,  114,  281,  190,  260,  223,   49,  227,  227,
      286,  236,  224,  114,  216,  287,   55,  169,  174,  140,
      174,  135,  141,  115,  134,  114,  133,  140,  116,  142,
      141,  132,  174,  192,  143,  142,  174,  195,  239,  131,
      143,  266,  196,  130,  129,  128,  140,  140,  200,  199,
      199,  144,  204,  267,  114,  248,  243,  245,  127,  144,
       63,  244,  197,   49,  115,   55,  152,   49,  146,  116,
      268,   49,  114,  153,   49,  147,  154,  206,  202,  202,
      148,  155,  154,   49,  152,  251,  152,  155,   49,   49,
       49,  153,  271,  213,  209,  214,  255,  149,  156,  210,

      272,  256,   49,   49,  152,   63,   49,   49,   49,   49,
       49,  213,  158,  114,  257,  159,  156,  273,  216,  211,
      160,   49,   49,  171,  114,   99,   98,   97,  172,   96,
      140,  114,  140,  199,  222,  199,  216,  161,  114,  223,
      200,  171,  243,   91,  152,  201,  172,  244,  200,   90,
      114,  213,   87,  201,  214,   49,  152,  114,   49,  215,
      171,   49,  202,  213,  202,  172,  255,  214,  288,   49,
       49,  256,  215,  289,  114,  296,  216,  292,  304,   49,
      285,  114,  297,  305,  293,   49,   49,  298,  216,  294,
      306,  300,  114,  296,  114,  292,  301,  292,  114,   49,

      297,  292,  293,  302,  293,  298,   49,  294,  307,  294,
      114,  114,  114,  308,  292,  313,  346,  346,  114,  114,
      300,  309,  314,  346,  346,  301,  310,  315,  316,  318,
      346,  281,  302,  317,  319,  320,  114,  304,  286,  346,
      302,  302,  305,  287,  114,  300,  323,  292,  346,  306,
      301,  324,  220,  114,  307,  327,  313,  302,  325,  282,
      346,  346,  293,  329,  296,  346,  346,  328,  330,  114,
      114,  297,  313,  313,  346,  346,  298,  114,  114,  314,
      314,  313,  346,  346,  315,  315,  114,  316,  331,  313,
      288,  346,  284,  332,  220,  289,  329,  114,  304,  302,

      346,  330,  285,  305,  300,  114,  346,  336,  114,  334,
      306,  114,  337,  346,  320,  323,  335,  346,  338,  325,
      324,  336,  114,  339,  323,  292,  337,  325,  114,  324,
      325,  292,  293,  325,  346,  346,  325,  294,  293,  114,
      346,  220,  292,  294,  341,  114,  296,  114,  313,  309,
      313,  314,  346,  297,  310,  329,  342,  331,  298,  114,
      330,  114,  311,  320,  346,  220,  346,  114,  346,  300,
      346,  318,  346,  300,  301,  323,  319,  336,  301,  346,
      344,  302,  337,  302,  114,  302,  304,  345,  346,  325,
      114,  305,  114,  313,  338,  313,  346,  346,  306,  321,

      314,  114,  314,  114,  313,  315,  325,  315,  346,  114,
      346,  329,  320,  323,  346,  346,  330,  346,  324,  336,
      346,  346,  323,  346,  337,  325,  346,  324,  346,  346,
      346,  325,  346,  346,  325,   54,   54,   62,   62,   55,
       55,   63,   63,  113,  113,  139,  139,  145,  145,  151,
      151,  157,  157,  114,  114,  170,  170,  140,  140,  198,
      198,  152,  152,  212,  212,  219,  219,  238,  238,  250,
      250,  259,  259,  265,  265,  270,  270,  291,  291,  299,
      299,  312,  312,  322,  322,  326,  326,  333,  333,  340,
      340,  343,  343,    3,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346
    } ;

static const flex_int16_t yy_chk[1255] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    6,    6,    6,    7,    8,    9,  203,
        8,   10,    7,   12,   11,   16,    5,   30,   10,   16,
       12,   30,    8,   11,   18,  375,   18,   20,   12,   19,
       19,   19,   20,   18,   23,    9,   26,   27,   45,    8,

       25,   23,   26,   27,  203,   12,   21,   21,   21,   21,
       25,  129,  129,   25,   35,   54,   25,   21,   54,   35,
       21,   21,   21,   38,   39,   38,   55,   49,   63,   39,
       54,   21,   49,   50,   50,   50,   21,   59,   45,   51,
       51,   51,   21,   22,   22,   22,   22,   54,   58,   50,
       52,   52,   52,   63,   22,   55,   57,   22,   22,   57,
       65,  105,   70,   58,   71,  119,   57,   59,   22,   71,
      119,   57,   70,   22,  373,   65,  371,   70,  370,   22,
       29,   29,   29,  105,  124,  124,  124,  353,   57,   29,
       29,   29,   29,   29,   29,   29,  162,  162,  162,  150,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   62,
       64,   85,  279,  247,   85,  149,   62,   64,  150,  279,
       64,   69,   69,   69,   62,   64,   85,   72,   72,   72,
      149,   69,   69,  347,   69,   75,  247,   72,   72,  164,
       72,   62,   64,   85,  164,   69,   69,   86,   75,   75,
       69,   72,   72,  320,   86,  249,   72,   73,   73,   73,
       73,   74,   86,   74,   75,   74,   74,   74,   73,  237,
       75,   73,   73,  161,  103,  104,  109,  103,  104,   86,
      249,  274,   73,  109,  103,  104,  109,   73,  161,  103,

      104,  109,  166,   73,   76,   76,   76,  166,  237,  192,
      120,  120,  120,   76,   76,   76,  103,  104,  109,  192,
      120,  120,  261,  120,   76,   76,   76,   76,   76,   76,
       77,   77,   77,   77,  120,  120,  110,  169,  234,  120,
      233,   77,  169,  110,   77,   77,  110,  113,  111,  115,
      111,  110,  111,  111,  111,   77,  123,  113,  231,  115,
       77,  116,  113,  118,  115,  140,   77,  283,  110,  123,
      123,  116,  140,  118,  283,  121,  116,  121,  118,  121,
      121,  121,  125,  125,  125,  123,  126,  126,  141,  139,
      144,  123,  139,  125,  140,  125,  206,  230,  141,  139,

      144,  220,  126,  141,  139,  144,  206,  125,  126,  142,
      143,  125,  142,  143,  145,  152,  204,  145,  152,  142,
      143,  139,  217,  147,  142,  143,  147,  217,  269,  145,
      175,  175,  175,  147,  148,  190,  278,  148,  147,  189,
      152,  142,  143,  151,  148,  187,  145,  153,  278,  148,
      151,  225,  269,  151,  154,  147,  225,  153,  151,  280,
      186,  154,  153,  155,  154,  157,  148,  156,  185,  154,
      155,  280,  157,  155,  159,  151,  281,  156,  155,  295,
      157,  159,  156,  160,  159,  183,  154,  182,  281,  159,
      160,  295,  165,  160,  167,  155,  296,  157,  160,  163,

      163,  163,  165,  168,  167,  181,  159,  165,  296,  167,
      163,  170,  163,  168,  179,  160,  303,  171,  168,  172,
      177,  170,  251,  303,  163,  251,  170,  171,  163,  172,
      178,  173,  171,  173,  172,  173,  173,  173,  176,  176,
      176,  191,  193,  178,  178,  193,  174,  251,  191,  176,
      158,  176,  193,  191,  226,  226,  226,  193,  194,  178,
      146,  194,  138,  176,  239,  178,  195,  176,  194,  195,
      191,  239,  196,  194,  193,  196,  195,  137,  136,  135,
      132,  195,  196,  131,  199,  197,  198,  196,  197,  198,
      194,  130,  202,  239,  199,  197,  198,  128,  195,  199,

      197,  198,  202,  127,  196,  200,  201,  202,  200,  201,
      122,  205,  213,  216,  205,  200,  201,  197,  198,  205,
      200,  201,  213,  216,  207,  208,  285,  213,  216,  117,
      114,  207,  208,  112,  207,  208,  205,  200,  201,  207,
      208,  285,  108,  209,  210,  211,  106,  275,  285,  275,
      209,  210,  211,  209,  210,  211,  207,  208,  209,  210,
      211,  275,  102,  212,  214,  306,  275,  277,  100,  277,
      212,  214,   99,  212,  214,  209,  210,  211,  212,  214,
      306,  277,  215,  219,  221,   98,  277,  306,   97,  215,
      222,  223,  215,  219,  221,  212,  214,  215,  219,  221,

      222,  223,  224,  282,  236,  222,  223,  227,  227,  227,
      282,  236,  224,  240,  215,  282,  236,  224,  227,  238,
      227,   96,  238,  240,   95,  242,   93,  241,  240,  238,
      241,   92,  227,  236,  238,  242,  227,  241,  243,   91,
      242,  243,  241,   90,   89,   88,  244,  245,  243,  244,
      245,  238,  248,  243,  252,  248,  244,  245,   87,  241,
      248,  244,  245,   83,  252,  246,  250,   82,  246,  252,
      243,   81,  254,  250,   80,  246,  250,  248,  244,  245,
      246,  250,  254,   79,  253,  255,  256,  254,   78,   68,
       67,  253,  255,  256,  253,  255,  256,  246,  250,  253,

      255,  256,   66,   61,  257,  258,   60,   56,   53,   48,
       47,  257,  258,  259,  257,  258,  253,  255,  256,  257,
      258,   46,   44,  259,  260,   43,   42,   41,  259,   40,
      265,  266,  267,  265,  260,  267,  257,  258,  268,  260,
      265,  266,  267,   37,  270,  265,  266,  267,  268,   36,
      271,  270,   34,  268,  270,   33,  272,  273,   32,  270,
      271,   31,  265,  272,  267,  271,  272,  273,  284,   28,
       24,  272,  273,  284,  286,  287,  270,  286,  289,   17,
      284,  288,  287,  289,  286,   15,   14,  287,  272,  286,
      289,  288,  291,  298,  292,  291,  288,  292,  293,   13,

      298,  293,  291,  288,  292,  298,    4,  291,  293,  292,
      299,  294,  297,  293,  294,  297,    3,    0,  300,  301,
      299,  294,  297,    0,    0,  299,  294,  297,  300,  301,
        0,  308,  299,  300,  301,  302,  304,  305,  308,    0,
      300,  301,  305,  308,  307,  302,  304,  307,    0,  305,
      302,  304,  309,  310,  307,  309,  310,  302,  304,  307,
        0,    0,  309,  310,  311,    0,    0,  309,  310,  312,
      313,  311,  312,  313,    0,    0,  311,  316,  314,  312,
      313,  314,    0,    0,  312,  313,  315,  316,  314,  315,
      317,    0,  316,  314,  318,  317,  315,  319,  321,  316,

        0,  315,  317,  321,  318,  322,    0,  319,  323,  318,
      321,  324,  319,    0,  325,  322,  318,    0,  323,  319,
      322,  324,  326,  323,  325,  326,  324,  322,  327,  325,
      323,  327,  326,  324,    0,    0,  325,  326,  327,  328,
        0,  329,  328,  327,  329,  330,  332,  331,  330,  328,
      331,  329,    0,  332,  328,  330,  329,  331,  332,  333,
      330,  334,  331,  335,    0,  336,    0,  337,    0,  333,
        0,  334,    0,  335,  333,  336,  334,  337,  335,    0,
      336,  333,  337,  334,  338,  335,  339,  336,    0,  337,
      340,  339,  341,  340,  338,  341,    0,    0,  339,  338,

      340,  342,  341,  343,  342,  340,  338,  341,    0,  344,
        0,  342,  345,  343,    0,    0,  342,    0,  343,  344,
        0,    0,  345,    0,  344,  343,    0,  345,    0,    0,
        0,  344,    0,    0,  345,  348,  348,  349,  349,  350,
      350,  351,  351,  352,  352,  354,  354,  355,  355,  356,
      356,  357,  357,  358,  358,  359,  359,  360,  360,  361,
      361,  362,  362,  363,  363,  364,  364,  365,  365,  366,
      366,  367,  367,  368,  368,  369,  369,  372,  372,  374,
      374,  376,  376,  377,  377,  378,  378,  379,  379,  380,
      380,  381,  381,  346,  346,  346,  346,  346,  346,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[66] =
    {   0,
0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "icg.l"
#line 10 "icg.l"



#include <stdio.h>
#include "y.tab.h"

void yyerror(const char* error_msg);
void comment();
void count();
int check_type();
void printcode();
void printcode2();
void printcode3();
#line 880 "lex.yy.c"
#line 881 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 25 "icg.l"

#line 1100 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 347 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1194 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "icg.l"
{;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 27 "icg.l"
{;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 28 "icg.l"
{printf("%s\n", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 29 "icg.l"
{printf("%s\n", yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "icg.l"
{ printcode(); return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "icg.l"
{ printcode(); return(CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "icg.l"
{ printcode(); return(CONST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "icg.l"
{ printcode(); return(CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "icg.l"
{ printcode(); return(DO); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "icg.l"
{ printcode(); return(DOUBLE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "icg.l"
{ printcode(); return(ELSE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "icg.l"
{ printcode(); return(FLOAT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "icg.l"
{ printcode(); return(FOR); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "icg.l"
{ printcode(); return(IF); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "icg.l"
{ printcode(); return(INT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "icg.l"
{ printcode(); return(RETURN); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "icg.l"
{ printcode(); return(SIZEOF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "icg.l"
{ printcode(); return(VOID); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "icg.l"
{ printcode(); return(WHILE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "icg.l"
{ printcode(); return(check_type()); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 50 "icg.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 51 "icg.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 52 "icg.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 53 "icg.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 55 "icg.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 56 "icg.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 57 "icg.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 59 "icg.l"
{ printcode(); return(STRING_LITERAL); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "icg.l"
{ printcode(); return(INC_OP); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "icg.l"
{ printcode(); return(DEC_OP); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "icg.l"
{ printcode(); return(PTR_OP); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "icg.l"
{ printcode(); return(AND_OP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "icg.l"
{ printcode(); return(OR_OP); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "icg.l"
{ printcode(); return(LE_OP); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "icg.l"
{ printcode(); return(GE_OP); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "icg.l"
{ printcode(); return(EQ_OP); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "icg.l"
{ printcode(); return(NE_OP); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 71 "icg.l"
{ printcode(); return(';'); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "icg.l"
{ printcode(); return('{'); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "icg.l"
{ printcode(); return('}'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "icg.l"
{ printcode(); return(','); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "icg.l"
{ printcode(); return(':'); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "icg.l"
{ printcode(); return('='); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 77 "icg.l"
{ printcode(); return('('); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 78 "icg.l"
{ printcode(); return(')'); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 79 "icg.l"
{ printcode(); return('['); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "icg.l"
{ printcode(); return(']'); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "icg.l"
{ printcode(); return('.'); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "icg.l"
{ printcode(); return('&'); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "icg.l"
{ printcode(); return('!'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "icg.l"
{ printcode(); return('~'); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "icg.l"
{ printcode(); return('-'); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "icg.l"
{ printcode(); return('+'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "icg.l"
{ printcode(); return('*'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "icg.l"
{ printcode(); return('/'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "icg.l"
{ printcode(); return('%'); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 90 "icg.l"
{ printcode(); return('<'); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 91 "icg.l"
{ printcode(); return('>'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 92 "icg.l"
{ printcode(); return('^'); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 93 "icg.l"
{ printcode(); return('|'); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 94 "icg.l"
{ printcode(); return('?'); }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 95 "icg.l"
{printcode3();}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 96 "icg.l"
{ printcode2(); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 98 "icg.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 100 "icg.l"
ECHO;
	YY_BREAK
#line 1498 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 347 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 347 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 346);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 100 "icg.l"


int yywrap()
{
	return(1);
}


void printcode3(){
	printf("\n");
}

int column = 0;
void printcode2(){
	printf(" ");
}
void printcode()
{
}


int check_type()
{
	return(IDENTIFIER);
}
