
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[344] =
    {   0,
       61,   61,   65,   63,   62,   61,   49,   63,   63,   55,
       48,   63,   43,   44,   53,   52,   40,   51,   47,   54,
       22,   22,   41,   37,   56,   42,   57,   60,   20,   20,
       45,   46,   58,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   38,   59,   39,   50,    0,    0,   62,
       62,   61,   36,    0,    0,   27,    0,    0,    0,   39,
       31,    0,    0,    0,    0,   28,   29,   30,   25,    0,
        1,   26,   21,    0,   22,   22,   46,   38,   45,   33,
       35,   34,   20,    0,    0,   20,   20,   20,    9,   20,
       20,   20,   14,   20,   20,   20,   20,   20,   32,   27,

        0,    0,    1,    0,   23,   23,    0,    0,    1,    0,
       25,    0,    0,    0,    0,    1,    1,    1,   25,    0,
       26,   21,    0,   24,   20,   20,   20,   20,   20,   20,
       13,   15,   20,   20,   20,   20,    0,    0,   27,    0,
        0,    0,    1,    1,    1,    1,    1,    0,    0,    0,
       23,    0,    0,    0,    1,    1,    1,    1,    1,    0,
       25,    0,    0,    2,    0,    1,    1,    1,    1,    1,
        0,   25,    0,   26,   24,   20,    6,   20,   20,   20,
       11,   20,   20,   20,   18,   20,   27,    0,    0,    0,
        2,    0,    1,    1,    1,    1,    1,    1,    1,    0,

       23,    0,    0,    0,    2,    0,    1,    1,    1,    1,
        1,    1,    1,    0,    2,    0,    0,    2,    1,    1,
        1,    1,    0,   25,    5,    7,   20,   20,   12,   20,
       20,   19,    0,    2,    0,    0,   27,    2,    0,    1,
        1,    1,    1,    0,    0,    2,    0,    0,   23,    2,
        0,    1,    1,    1,    1,    1,    1,   20,   10,   16,
       17,    1,    1,    1,    1,    0,    1,    1,    1,    1,
       20,    0,    8,    0,    0,    0,    0,    4,    0,    0,
        0,    0,    0,    1,    0,    1,    3,    0,    4,    0,
        0,    1,    1,    1,    1,    0,    0,    0,    0,    1,

        1,    1,    1,    0,    2,    0,    1,    1,    1,    1,
        1,    1,    0,    2,    0,    1,    3,    1,    1,    1,
        1,    1,    0,    4,    2,    1,    1,    1,    1,    0,
        2,    0,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       27,   27,   27,   27,   27,   30,   27,   27,   27,   27,
       27,   27,   27,   27,   31,   27,   27,   27,   27,   27,
       32,   33,   34,   35,   27,    1,   36,   37,   38,   39,

       40,   41,   27,   42,   43,   27,   44,   45,   27,   46,
       47,   27,   27,   48,   49,   50,   51,   52,   53,   27,
       27,   54,   55,   56,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[379] =
    {   0,
        0,    0,  849,  823,   57,   60,   47,   63,   49,   52,
       64,   69,  812,  808,  805,   60,  804,   68,   70,   67,
       86,  121,   58,  801,   89,   76,   77,  793,  155,  102,
      788,  785,  782,  746,   73,  744,  740,   64,   77,  743,
      739,  732,  736,  752,   73,  749,  746,  745,  106,  130,
      140,  143,  738,  147,   92,  732,  207,  118,   81,  730,
      729,  208,  125,  209,  151,  723,  721,  717,  225,  211,
      142,  253,  282,  214,  205,  317,  714,  713,  710,  706,
      697,  690,    0,  243,  257,  661,  657,  643,  629,  630,
      628,  626,    0,  621,  613,  608,  616,  605,  623, 1185,

      632,  245,  256,  138,  615, 1185,  623,  274,  293,  300,
      604,  234,  596,  312,  325,  589,  326,  144,  351,  335,
      582,  342,  159,  345,  563,  533,  114,  541,  512,  509,
        0,    0,  486,  487,  467,  459,  382,  291,  328,  391,
      395,  364,  396,  469,  404,  413,  213,  170,  417,  157,
      420,  429,  431,  440,  442,  458,  453,  464,  261,  450,
      460,  267,  470,  273,  478,  481,  343,  482,  489,  490,
      495,  454,  498,  501,  447,  415,    0,  407,  412,  406,
        0,  390,  377,  374,    0,  371,  390,  516,  168,  520,
      522,  538,  544,  555,  557,  551,  573,  579,  571,  270,

      363,  583,  292,  592,  601,  605,  614,  618,  627,  626,
      639,  640,  643,  365, 1185,  651,  345,  652,  663,  664,
      665,  371,  547,  666,    0,    0,  296,  277,    0,  262,
      227,    0,  681,  317,  685,  526,  687,  703,  699,  707,
      716,  720,  724,  150,  733,  299,  742,  570,  741,  755,
      758,  759,  771,  777,  783,  794,  795,  206,    0,    0,
        0,  796,  802,  815,  814,  199,  821,  822,  833,  834,
      198,  838,    0,  849,  334,  341,  400,  430,  530,  387,
      679,  569,  856,  832,  855,  852, 1185,  872,  873,  881,
      889,  492,  506,  890,  891,  897,  898,  911,  914,  436,

      915,  912,  595,  928,  929,  942,  946,  938,  955,  959,
      963,  972,  971,  925,  979,  980,  208,  981,  997,  998,
      999, 1000, 1023, 1024, 1025, 1041, 1042, 1043,  973, 1049,
     1050, 1063, 1066, 1067, 1069,  996, 1080, 1093, 1094, 1092,
     1100, 1101, 1185,  186, 1126, 1128, 1130, 1132, 1134,  158,
     1136, 1138, 1140, 1142, 1144, 1146, 1148, 1150, 1152, 1154,
     1156, 1158, 1160, 1162, 1164, 1166,  129,  127, 1168,  121,
     1170,   67, 1172, 1174, 1176, 1178, 1180, 1182
    } ;

static const flex_int16_t yy_def[379] =
    {   0,
      343,    1,  343,  344,  344,  343,  344,  345,  344,  344,
      344,  346,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,   29,
      344,  344,  344,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,  344,  344,  344,  344,  344,  344,  344,
      343,  343,  344,  345,  347,  344,  345,  345,  344,  344,
      344,  346,  348,  346,  346,  344,  344,  344,  344,  349,
      350,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,   29,  345,  346,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,  344,  343,

      347,  351,  352,  344,  344,  343,  348,  353,  354,  344,
      344,  349,  355,  349,  349,  350,  356,  350,  344,  344,
      344,  344,  344,  344,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,  351,  357,  349,  351,
      351,  351,  352,  350,  358,  352,  352,  344,  353,  359,
      349,  353,  353,  353,  354,  350,  360,  354,  354,  344,
      344,  355,  349,  344,  361,  356,  350,  356,  356,  356,
      344,  344,  344,  344,  344,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,  355,  357,  357,  351,
      345,  362,  358,  352,  358,  356,  358,  358,  358,  344,

      355,  359,  359,  353,  346,  363,  360,  354,  360,  356,
      360,  360,  360,  355,  343,  349,  355,  349,  364,  356,
      356,  350,  344,  344,   29,   29,   29,   29,   29,   29,
       29,   29,  357,  347,  351,  357,  349,  351,  351,  365,
      358,  358,  352,  344,  359,  348,  353,  359,  349,  353,
      353,  366,  360,  360,  354,  356,  356,   29,   29,   29,
       29,  358,  356,  358,  358,  344,  360,  356,  360,  360,
       29,  344,   29,  344,  367,  368,  367,  367,  367,  368,
      368,  368,  369,  370,  371,  372,  343,  369,  369,  369,
      369,  370,  370,  373,  370,  371,  371,  371,  371,  372,

      374,  372,  372,  369,  367,  375,  373,  370,  373,  373,
      373,  373,  371,  368,  376,  374,  355,  372,  374,  374,
      374,  374,  369,  369,  369,  377,  373,  373,  370,  371,
      371,  371,  378,  374,  374,  372,  373,  373,  373,  374,
      374,  374,    0,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343
    } ;

static const flex_int16_t yy_nxt[1244] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   30,
       29,   31,    4,   32,   33,   29,   34,   35,   36,   37,
       38,   29,   39,   29,   29,   29,   29,   40,   41,   29,
       29,   42,   43,   29,   44,   45,   46,   47,   50,   51,
       50,   51,   52,   51,   49,   55,   49,  300,   56,   49,
       53,   63,   61,   66,   49,   49,   60,   49,   48,   70,
       57,   49,   77,   67,   71,   49,   64,   49,   69,   69,
       49,   59,   68,   49,   49,   58,   78,  100,   49,   81,

       82,   65,   72,   49,   73,   73,   49,   84,   91,   79,
       92,   85,   80,   74,   87,   75,   75,   93,   70,   88,
      343,  292,   94,   71,  101,   74,  104,  280,   99,  277,
       75,   50,   51,   50,  106,   57,   75,   72,   49,   76,
       76,   51,   51,   51,   51,   52,   51,   49,   74,   55,
       75,   75,   56,  343,  117,   49,  117,  107,  116,  118,
       74,  118,  178,  179,   57,   75,  201,   49,   64,  202,
      113,   75,   49,   83,   83,  148,   49,  124,  124,   58,
      188,   83,   83,   83,   83,   83,   48,   49,  266,  203,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,

       83,   83,   83,   83,   83,   83,   83,   83,   83,   55,
       63,   63,   56,  113,  200,  343,   49,  105,  105,  102,
      162,  108,   49,  114,  103,   64,  109,  123,  115,  123,
      194,   49,  124,  124,   75,   75,  113,  273,  272,   58,
       65,   65,   49,   69,   69,   55,  114,  138,   56,   75,
      139,  115,  110,  111,  111,   75,  271,  140,   55,   63,
       57,  144,  141,  343,  110,  111,   48,  261,  145,  111,
       49,  119,  119,  146,   64,   58,  150,  142,  208,  214,
      120,  121,  121,  151,  215,   70,  152,   49,  147,   65,
       71,  153,  120,  121,  113,   63,  187,  121,   72,   49,

       73,   73,  156,  188,  202,  157,  154,  260,  106,   74,
      158,  122,  122,  160,  113,  160,  259,   49,  161,  161,
      244,   74,  100,  189,  163,  159,  122,  113,  113,  164,
      113,  107,  122,   72,   49,   76,   76,  165,  169,  278,
      114,  258,  166,  170,   74,  115,   75,   75,  173,  101,
      173,  279,   49,  174,  174,  117,   74,  162,  281,   49,
      118,   75,   49,  124,  124,  282,  113,   75,   49,  119,
      119,  122,  122,  175,  175,  162,  140,  214,  171,  172,
      172,  141,  343,  117,  138,  175,  122,  139,  118,  175,
      171,  172,  122,  138,  140,  172,  139,  138,   55,  141,

      139,  144,  162,  190,  281,  278,  138,  192,  191,  196,
      232,  282,  193,  194,  142,   55,  197,  279,  144,  150,
      231,  198,  113,  142,  230,  145,  151,  142,  147,  152,
      146,  150,  114,  150,  153,  278,  199,  115,  151,  229,
      151,  204,  113,  206,   63,  147,  205,  279,  207,  154,
      228,  156,  152,  318,  227,  150,  226,  153,  225,  208,
      303,  154,  210,  154,   49,  211,   63,   49,  161,  161,
      212,   49,  113,  156,  159,  167,  157,   49,  161,  161,
      217,  158,  163,  113,  113,  213,  167,   49,  111,  111,
      114,  113,  113,  219,  169,  218,  159,  293,  220,  170,

      111,  221,  219,  186,  111,  185,  222,  220,  223,  308,
      223,  293,   49,  224,  224,   49,  174,  174,   49,  174,
      174,  187,  138,  308,   55,  139,  184,   56,  233,  121,
      121,  187,  190,  234,  102,  278,  183,   57,  188,  103,
      236,  121,  283,  237,  182,  121,  138,  284,  189,  196,
      140,  181,  142,  113,   58,  238,  240,   55,  189,  138,
      144,  241,  196,  169,   49,  224,  224,  145,  170,  197,
      239,  287,  146,  113,  198,  138,  199,  180,  196,  201,
      177,  138,  202,  197,  196,  242,  281,  147,  198,  199,
      243,  240,  201,  282,  150,  245,  241,  287,  176,   49,

      246,  151,  203,   63,  204,  199,  167,  248,  162,   64,
      105,  199,  318,  108,  249,  203,  150,  152,  109,  303,
       63,   49,  250,  210,  154,  343,  252,  156,  113,  150,
      157,  253,   49,   65,  343,  158,  210,  251,  169,  211,
       49,  150,  150,  170,  212,  113,  213,  136,  210,  210,
      159,  254,  252,  113,  113,  211,  255,  253,  135,  213,
      212,  134,  133,  114,  165,  217,  113,  113,  115,  166,
      132,  213,  213,  131,  130,  169,  219,  221,  129,  128,
      257,  220,  167,   49,  224,  224,  187,  138,  127,  113,
      139,  285,  126,  233,  172,  172,  286,  140,   55,  114,

      125,  113,  141,  282,  115,  138,  172,   49,  139,  236,
      172,  140,  263,  189,   49,  192,  141,  142,  138,  197,
      193,  196,  138,   49,  264,  196,   55,   49,  240,  144,
       49,   49,  242,  241,   49,  142,  145,  194,   49,  265,
       49,  146,  201,  113,  150,  245,   49,   49,  199,   49,
       63,  151,  199,  114,  152,   49,  147,  150,  115,  153,
      113,  248,   49,   49,  151,  203,   49,  206,  268,   49,
      152,  211,  207,  150,  154,  153,  269,   98,   97,  150,
      210,   96,   95,  252,   90,   63,  210,  154,  253,  254,
       89,  270,  156,   86,  208,  157,  113,  113,  138,   49,

      158,  196,   49,  213,  113,   49,  169,  219,  197,  213,
       49,  170,  220,  198,  169,  159,  113,  138,   49,  170,
      196,   49,   49,  150,  113,   49,  197,  240,  199,   49,
      210,  198,  241,  211,  169,  150,  113,  293,  212,  170,
       49,  274,  210,  275,  294,  252,  211,  199,  343,  295,
      253,  212,  274,  213,  275,   49,  343,  113,  113,  343,
      276,  289,  343,  343,  301,  213,   49,  297,  290,  302,
      343,  276,  298,  291,  113,  113,  303,  289,  289,  299,
      343,  343,  343,  113,  290,  290,  289,  343,  343,  291,
      291,  113,  113,  304,  289,  310,  293,  343,  305,  113,

      113,  306,  311,  294,  343,  343,  307,  312,  295,  297,
      313,  343,  343,  113,  298,  314,  317,  113,  343,  343,
      343,  299,  299,  315,  301,  343,  297,  320,  316,  302,
      113,  298,  321,  289,  278,  299,  303,  285,  299,  322,
      304,  283,  286,  293,  217,  279,  284,  324,  113,  282,
      294,  310,  343,  343,  290,  295,  343,  113,  326,  325,
      310,  113,  343,  327,  310,  113,  343,  311,  310,  343,
      343,  311,  312,  113,  113,  328,  312,  310,  293,  343,
      329,  217,  113,  313,  326,  294,  343,  343,  281,  327,
      295,  297,  333,  301,  343,  299,  331,  334,  302,  113,

      113,  113,  317,  332,  322,  303,  343,  343,  301,  320,
      335,  333,  320,  302,  321,  336,  334,  321,  343,  343,
      303,  322,  322,  322,  322,  113,  113,  113,  289,  289,
      289,  343,  343,  343,  343,  290,  290,  306,  343,  343,
      291,  291,  307,  217,  113,  113,  338,  310,  310,  343,
      343,  113,  113,  311,  326,  328,  343,  343,  339,  327,
      308,  297,  315,  343,  343,  317,  298,  316,  217,  113,
      343,  113,  343,  299,  299,  297,  343,  343,  320,  333,
      298,  335,  113,  341,  334,  310,  318,  299,  343,  343,
      342,  322,  311,  322,  113,  113,  113,  312,  310,  310,

      343,  343,  113,  317,  320,  311,  326,  343,  343,  321,
      312,  327,  333,  320,  343,  343,  322,  334,  321,  343,
      343,  343,  343,  343,  322,  322,   54,   54,   62,   62,
       55,   55,   63,   63,  112,  112,  137,  137,  143,  143,
      149,  149,  155,  155,  113,  113,  168,  168,  138,  138,
      195,  195,  150,  150,  209,  209,  216,  216,  235,  235,
      247,  247,  256,  256,  262,  262,  267,  267,  288,  288,
      296,  296,  309,  309,  319,  319,  323,  323,  330,  330,
      337,  337,  340,  340,    3,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343
    } ;

static const flex_int16_t yy_chk[1244] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    6,    6,    6,    7,    8,    9,  372,    8,   10,
        7,   12,   11,   16,    5,   23,   10,   16,   12,   20,
        8,   11,   23,   18,   20,   18,   12,   19,   19,   19,
       45,    9,   18,   26,   27,    8,   25,   55,   59,   26,

       27,   12,   21,   21,   21,   21,   25,   30,   38,   25,
       38,   30,   25,   21,   35,   21,   21,   39,   49,   35,
       58,  370,   39,   49,   55,   21,   59,  368,   45,  367,
       21,   50,   50,   50,   63,   58,   21,   22,   22,   22,
       22,   51,   51,   51,   52,   52,   52,   50,   22,   54,
       22,   22,   54,   65,   71,  104,  118,   63,  350,   71,
       22,  118,  127,  127,   54,   22,  150,  244,   65,  150,
      189,   22,   29,   29,   29,  104,  123,  123,  123,   54,
      189,   29,   29,   29,   29,   29,  344,  148,  244,  150,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   57,
       62,   64,   57,   70,  148,  147,  266,   62,   64,   57,
      317,   64,   75,   70,   57,   62,   64,   74,   70,   74,
      147,   74,   74,   74,   75,   75,  112,  271,  266,   57,
       62,   64,   69,   69,   69,   84,  112,  102,   84,   75,
      102,  112,   69,   69,   69,   75,  258,  102,  103,   85,
       84,  103,  102,  159,   69,   69,   85,  231,  103,   69,
       72,   72,   72,  103,   85,   84,  108,  102,  159,  162,
       72,   72,   72,  108,  162,  164,  108,  200,  103,   85,
      164,  108,   72,   72,  203,  109,  138,   72,   73,   73,

       73,   73,  109,  138,  203,  109,  108,  230,  246,   73,
      109,   73,   73,  110,  114,  110,  228,  110,  110,  110,
      200,   73,  234,  138,  114,  109,   73,  115,  117,  114,
      139,  246,   73,   76,   76,   76,   76,  115,  117,  275,
      139,  227,  115,  117,   76,  139,   76,   76,  120,  234,
      120,  275,  120,  120,  120,  167,   76,  217,  276,  122,
      167,   76,  124,  124,  124,  276,  142,   76,  119,  119,
      119,  122,  122,  124,  124,  201,  142,  214,  119,  119,
      119,  142,  214,  222,  137,  124,  122,  137,  222,  124,
      119,  119,  122,  140,  137,  119,  140,  141,  143,  137,

      141,  143,  187,  140,  280,  277,  145,  141,  140,  145,
      186,  280,  141,  143,  137,  146,  145,  277,  146,  149,
      184,  145,  151,  140,  183,  146,  149,  141,  143,  149,
      146,  152,  151,  153,  149,  278,  145,  151,  152,  182,
      153,  152,  154,  153,  155,  146,  152,  278,  153,  149,
      180,  155,  154,  300,  179,  157,  178,  154,  176,  155,
      300,  152,  157,  153,  175,  157,  158,  160,  160,  160,
      157,  172,  163,  158,  155,  156,  158,  161,  161,  161,
      165,  158,  163,  166,  168,  157,  144,  163,  161,  161,
      165,  169,  170,  166,  168,  165,  158,  292,  166,  168,

      161,  169,  170,  136,  161,  135,  169,  170,  171,  292,
      171,  293,  171,  171,  171,  173,  173,  173,  174,  174,
      174,  188,  190,  293,  191,  190,  134,  191,  188,  174,
      174,  236,  190,  188,  191,  279,  133,  190,  236,  191,
      192,  174,  279,  192,  130,  174,  193,  279,  188,  193,
      192,  129,  190,  196,  191,  192,  193,  194,  236,  195,
      194,  193,  195,  196,  223,  223,  223,  194,  196,  195,
      192,  282,  194,  199,  195,  197,  193,  128,  197,  248,
      126,  198,  248,  199,  198,  197,  282,  194,  199,  195,
      197,  198,  202,  282,  204,  202,  198,  303,  125,  121,

      202,  204,  248,  205,  204,  197,  116,  206,  113,  204,
      205,  198,  303,  205,  206,  202,  207,  206,  205,  303,
      208,  111,  206,  207,  204,  107,  207,  208,  210,  209,
      208,  207,  105,  205,  101,  208,  209,  206,  210,  209,
       99,  211,  212,  210,  209,  213,  207,   98,  211,  212,
      208,  211,  212,  216,  218,  213,  211,  212,   97,  209,
      213,   96,   95,  216,  218,  219,  220,  221,  216,  218,
       94,  211,  212,   92,   91,  219,  220,  221,   90,   89,
      219,  220,  221,  224,  224,  224,  233,  235,   88,  237,
      235,  281,   87,  233,  224,  224,  281,  235,  233,  237,

       86,  239,  235,  281,  237,  238,  224,   82,  238,  240,
      224,  239,  240,  233,   81,  238,  239,  235,  241,  240,
      238,  241,  242,   80,  240,  242,  243,   79,  241,  243,
       78,   77,  242,  241,   68,  238,  243,  242,   67,  240,
       66,  243,  245,  249,  247,  245,   61,   60,  241,   56,
      245,  247,  242,  249,  247,   53,  243,  250,  249,  247,
      251,  252,   48,   47,  250,  245,   46,  250,  252,   44,
      251,  252,  250,  253,  247,  251,  252,   43,   42,  254,
      253,   41,   40,  253,   37,  255,  254,  250,  253,  254,
       36,  252,  255,   34,  254,  255,  256,  257,  262,   33,

      255,  262,   32,  253,  263,   31,  256,  257,  262,  254,
       28,  256,  257,  262,  263,  255,  265,  264,   24,  263,
      264,   17,   15,  267,  268,   14,  265,  264,  262,   13,
      267,  265,  264,  267,  268,  269,  270,  284,  267,  268,
        4,  272,  269,  272,  284,  269,  270,  264,    3,  284,
      269,  270,  274,  267,  274,  272,    0,  285,  283,    0,
      272,  283,    0,    0,  286,  269,  274,  285,  283,  286,
        0,  274,  285,  283,  288,  289,  286,  288,  289,  285,
        0,    0,    0,  290,  288,  289,  290,    0,    0,  288,
      289,  291,  294,  290,  291,  294,  295,    0,  290,  296,

      297,  291,  294,  295,    0,    0,  291,  294,  295,  296,
      297,    0,    0,  298,  296,  297,  299,  301,    0,    0,
        0,  296,  297,  298,  302,    0,  299,  301,  298,  302,
      304,  299,  301,  304,  305,  298,  302,  314,  299,  301,
      304,  305,  314,  308,  306,  304,  305,  306,  307,  314,
      308,  307,    0,    0,  306,  308,    0,  309,  307,  306,
      309,  310,    0,  307,  310,  311,    0,  309,  311,    0,
        0,  310,  309,  313,  312,  311,  310,  312,  329,    0,
      311,  315,  316,  313,  312,  329,    0,    0,  313,  312,
      329,  315,  316,  318,    0,  313,  315,  316,  318,  319,

      320,  321,  322,  315,  316,  318,    0,    0,  336,  319,
      320,  321,  322,  336,  319,  320,  321,  322,    0,    0,
      336,  319,  320,  321,  322,  323,  324,  325,  323,  324,
      325,    0,    0,    0,    0,  323,  324,  325,    0,    0,
      323,  324,  325,  326,  327,  328,  326,  327,  328,    0,
        0,  330,  331,  326,  327,  328,    0,    0,  326,  327,
      328,  330,  331,    0,    0,  332,  330,  331,  333,  334,
        0,  335,    0,  330,  331,  332,    0,    0,  333,  334,
      332,  335,  337,  333,  334,  337,  335,  332,    0,    0,
      333,  334,  337,  335,  340,  338,  339,  337,  338,  339,

        0,    0,  341,  342,  340,  338,  339,    0,    0,  340,
      338,  339,  341,  342,    0,    0,  340,  341,  342,    0,
        0,    0,    0,    0,  341,  342,  345,  345,  346,  346,
      347,  347,  348,  348,  349,  349,  351,  351,  352,  352,
      353,  353,  354,  354,  355,  355,  356,  356,  357,  357,
      358,  358,  359,  359,  360,  360,  361,  361,  362,  362,
      363,  363,  364,  364,  365,  365,  366,  366,  369,  369,
      371,  371,  373,  373,  374,  374,  375,  375,  376,  376,
      377,  377,  378,  378,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[65] =
    {   0,
0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ansi.l"
#line 10 "ansi.l"



#include <stdio.h>
#include "y.tab.h"
void yyerror(const char* error_msg);
void comment();
void count();
int check_type();
void printcode();
void printcode2();
void printcode3();
#line 875 "lex.yy.c"
#line 876 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 24 "ansi.l"

#line 1095 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 344 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1185 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 25 "ansi.l"
{;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 26 "ansi.l"
{;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 27 "ansi.l"
{printf("%s\n", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 28 "ansi.l"
{printf("%s\n", yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "ansi.l"
{ printcode(); return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "ansi.l"
{ printcode(); return(CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "ansi.l"
{ printcode(); return(CONST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "ansi.l"
{ printcode(); return(CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "ansi.l"
{ printcode(); return(DO); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "ansi.l"
{ printcode(); return(DOUBLE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "ansi.l"
{ printcode(); return(ELSE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "ansi.l"
{ printcode(); return(FLOAT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "ansi.l"
{ printcode(); return(FOR); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "ansi.l"
{ printcode(); return(IF); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "ansi.l"
{ printcode(); return(INT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "ansi.l"
{ printcode(); return(RETURN); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "ansi.l"
{ printcode(); return(SIZEOF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "ansi.l"
{ printcode(); return(VOID); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 45 "ansi.l"
{ printcode(); return(WHILE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "ansi.l"
{ printcode(); return(check_type()); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "ansi.l"
{ printcode();yylval=atoi(yytext); return(CONSTANT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "ansi.l"
{ printcode();yylval=atoi(yytext); return(CONSTANT); }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 51 "ansi.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 53 "ansi.l"
{ printcode(); yylval=atof(yytext);return(CONSTANT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 54 "ansi.l"
{ printcode(); yylval=atof(yytext);return(CONSTANT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 55 "ansi.l"
{ printcode(); yylval=atof(yytext);return(CONSTANT); }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 57 "ansi.l"
{ printcode(); return(STRING_LITERAL); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 60 "ansi.l"
{ printcode(); return(INC_OP); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 61 "ansi.l"
{ printcode(); return(DEC_OP); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 62 "ansi.l"
{ printcode(); return(PTR_OP); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 63 "ansi.l"
{ printcode(); return(AND_OP); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 64 "ansi.l"
{ printcode(); return(OR_OP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 65 "ansi.l"
{ printcode(); return(LE_OP); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 66 "ansi.l"
{ printcode(); return(GE_OP); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 "ansi.l"
{ printcode(); return(EQ_OP); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 68 "ansi.l"
{ printcode(); return(NE_OP); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 69 "ansi.l"
{ printcode(); return(';'); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "ansi.l"
{ printcode(); return('{'); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 71 "ansi.l"
{ printcode(); return('}'); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 72 "ansi.l"
{ printcode(); return(','); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 73 "ansi.l"
{ printcode(); return(':'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 74 "ansi.l"
{ printcode(); return('='); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 75 "ansi.l"
{ printcode(); return('('); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 76 "ansi.l"
{ printcode(); return(')'); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 77 "ansi.l"
{ printcode(); return('['); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 78 "ansi.l"
{ printcode(); return(']'); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 79 "ansi.l"
{ printcode(); return('.'); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 80 "ansi.l"
{ printcode(); return('&'); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 81 "ansi.l"
{ printcode(); return('!'); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 82 "ansi.l"
{ printcode(); return('~'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 83 "ansi.l"
{ printcode(); return('-'); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 84 "ansi.l"
{ printcode(); return('+'); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 85 "ansi.l"
{ printcode(); return('*'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 86 "ansi.l"
{ printcode(); return('/'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 87 "ansi.l"
{ printcode(); return('%'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 88 "ansi.l"
{ printcode(); return('<'); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 89 "ansi.l"
{ printcode(); return('>'); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 90 "ansi.l"
{ printcode(); return('^'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 91 "ansi.l"
{ printcode(); return('|'); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 92 "ansi.l"
{ printcode(); return('?'); }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 93 "ansi.l"
{printcode3();}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 94 "ansi.l"
{ printcode2(); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 96 "ansi.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 98 "ansi.l"
ECHO;
	YY_BREAK
#line 1488 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 344 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 344 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 343);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 98 "ansi.l"


int yywrap()
{
	return(1);
}


void printcode3(){
	printf("\n");
}

int column = 0;
void printcode2(){
	printf(" ");
}
void printcode()
{
	ECHO;
}


int check_type()
{
	return(IDENTIFIER);
}
