
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[358] =
    {   0,
        0,    0,   78,   76,   75,   75,   63,   76,   76,   69,
       62,   76,   57,   58,   67,   66,   54,   65,   61,   68,
       23,   23,   55,   51,   70,   56,   71,   74,   20,   20,
       59,   60,   72,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   52,   73,   53,   64,    0,    0,   50,
        0,    0,   28,    0,    0,    0,   36,   53,   45,   37,
        0,    0,    0,    0,   34,   42,   32,   43,   33,   44,
        0,   26,    0,    1,   35,   27,   22,    0,   23,    0,
       23,   60,   52,   59,   41,   47,   49,   48,   40,   20,
        0,    0,   38,   20,   20,   20,    9,   20,   20,   20,

       14,   20,   20,   20,   20,   20,   39,   46,   28,    0,
        0,    1,    0,   24,   24,    0,    0,    1,   29,    0,
       26,    0,    0,    0,    0,    1,    1,    1,   26,    0,
       27,   22,    0,   25,   21,   31,   30,   20,   20,   20,
       20,   20,   20,   13,   15,   20,   20,   20,   20,    0,
        0,   28,    0,    0,    0,    1,    1,    1,    1,    1,
        0,    0,    0,   24,    0,    0,    0,    1,    1,    1,
        1,    1,    0,   26,    0,    0,    2,    0,    1,    1,
        1,    1,    1,    0,   26,    0,   27,   25,   21,   20,
        6,   20,   20,   20,   11,   20,   20,   20,   18,   20,

       28,    0,    0,    0,    2,    0,    1,    1,    1,    1,
        1,    1,    1,    0,   24,    0,    0,    0,    2,    0,
        1,    1,    1,    1,    1,    1,    1,    0,    2,    0,
        0,    2,    1,    1,    1,    1,    0,   26,    5,    7,
       20,   20,   12,   20,   20,   19,    0,    2,    0,    0,
       28,    2,    0,    1,    1,    1,    1,    0,    0,    2,
        0,    0,   24,    2,    0,    1,    1,    1,    1,    1,
        1,   20,   10,   16,   17,    1,    1,    1,    1,    0,
        1,    1,    1,    1,   20,    0,    8,    0,    0,    0,
        0,    4,    0,    0,    0,    0,    0,    1,    0,    1,

        3,    0,    4,    0,    0,    1,    1,    1,    1,    0,
        0,    0,    0,    1,    1,    1,    1,    0,    2,    0,
        1,    1,    1,    1,    1,    1,    0,    2,    0,    1,
        3,    1,    1,    1,    1,    1,    0,    4,    2,    1,
        1,    1,    1,    0,    2,    0,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   30,    1,   38,   39,   40,   41,

       42,   43,   30,   44,   45,   30,   46,   47,   30,   48,
       49,   30,   30,   50,   51,   52,   53,   54,   55,   33,
       30,   56,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[393] =
    {   0,
        0,    0, 1030, 1011,  994, 1186,   43,   59,   45,   46,
       57,   66,  979,  973,   50,   64,  962,   67,   78,   86,
       94,  131,   54,  961,   85,   62,   99,  953,  167,  109,
      944,  943,  110,  887,   56,  881,  877,   40,   59,  877,
      872,  866,  862,  887,  111,  882,  881,  870,  103,  865,
      136,  125,  864,  140,  115,  119,  863,  861,  845,  841,
      154,  110,  221,  137,  833,  832,  830,  829,  821,  817,
      148,  207,  227,  143,  813,  224,  255,  163,  215,  291,
      318,  805,  801,  800,  114,  797,  794,  788,  150,    0,
      245,  266,  785,  756,  756,  741,  732,  729,  728,  726,

        0,  716,  713,  704,  712,  693,  718,  711, 1186,  724,
      282,  286,  112,  697, 1186,  697,  338,  344,  674,  308,
      671,  278,  662,  340,  356,  645,  363,  175,  364,  371,
      639,  368,  172,  383,  308,  635,  633,  595,  568,  150,
      576,  559,  559,    0,    0,  531,  539,  527,  517,  407,
      310,  391,  416,  425,  405,  421,  542,  434,  452,  261,
      185,  454,  247,  432,  458,  470,  441,  472,  540,  481,
      482,  275,  287,  483,  252,  493,  285,  495,  506,  350,
      507,  515,  518,  521,  514,  294,  524,  505,  516,  440,
        0,  414,  418,  415,    0,  397,  396,  384,    0,  390,

      403,  539,  167,  543,  559,  567,  573,  586,  587,  585,
      606,  607,  593,  241,  385,  362,  312,  613,  625,  626,
      627,  646,  655,  614,  664,  666,  667,  423, 1186,  675,
      383,  684,  691,  692,  693,  435,  459,  694,    0,    0,
      340,  336,    0,  322,  321,    0,  685,  223,  713,  516,
      704,  715,  721,  729,  740,  748,  749,  326,  637,  342,
      760,  673,  727,  769,  756,  778,  787,  789,  798,  807,
      814,  289,    0,    0,    0,  823,  825,  831,  827,  186,
      843,  839,  852,  851,  248,  648,    0,  867,  399,  456,
      509,  532,  569,  479,  541,  768,  871,  854,  873,  731,

     1186,  889,  890,  891,  907,  577,  628,  908,  862,  909,
      915,  926,  928,  589,  929,  796,  898,  932,  930,  946,
      952,  950,  954,  963,  971,  972,  970,  969,  983,  989,
      264,  980,  997, 1000, 1003, 1006, 1014, 1020, 1031, 1033,
     1037, 1039, 1035, 1051, 1053, 1055, 1057, 1059, 1076,  986,
     1080, 1082, 1084, 1078, 1096, 1102, 1186,  260, 1127, 1129,
     1131, 1133, 1135,  240, 1137, 1139, 1141, 1143, 1145, 1147,
     1149, 1151, 1153, 1155, 1157, 1159, 1161, 1163, 1165, 1167,
      236,  175, 1169,  143, 1171,   72, 1173, 1175, 1177, 1179,
     1181, 1183

    } ;

static const flex_int16_t yy_def[393] =
    {   0,
      357,    1,  357,  358,  358,  357,  358,  359,  358,  358,
      358,  360,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,   29,
      358,  358,  358,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,  358,  358,  358,  358,  358,  358,  358,
      359,  361,  358,  359,  359,  358,  358,  358,  358,  358,
      360,  362,  360,  360,  358,  358,  358,  358,  358,  358,
      358,  358,  363,  364,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,   29,
      359,  360,  358,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,  358,  358,  357,  361,
      365,  366,  358,  358,  357,  362,  367,  368,  358,  358,
      358,  363,  369,  363,  363,  364,  370,  364,  358,  358,
      358,  358,  358,  358,   80,  358,  358,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,  365,
      371,  363,  365,  365,  365,  366,  364,  372,  366,  366,
      358,  367,  373,  363,  367,  367,  367,  368,  364,  374,
      368,  368,  358,  358,  369,  363,  358,  375,  370,  364,
      370,  370,  370,  358,  358,  358,  358,  358,  358,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

      369,  371,  371,  365,  359,  376,  372,  366,  372,  370,
      372,  372,  372,  358,  369,  373,  373,  367,  360,  377,
      374,  368,  374,  370,  374,  374,  374,  369,  357,  363,
      369,  363,  378,  370,  370,  364,  358,  358,   29,   29,
       29,   29,   29,   29,   29,   29,  371,  361,  365,  371,
      363,  365,  365,  379,  372,  372,  366,  358,  373,  362,
      367,  373,  363,  367,  367,  380,  374,  374,  368,  370,
      370,   29,   29,   29,   29,  372,  370,  372,  372,  358,
      374,  370,  374,  374,   29,  358,   29,  358,  381,  382,
      381,  381,  381,  382,  382,  382,  383,  384,  385,  386,

      357,  383,  383,  383,  383,  384,  384,  387,  384,  385,
      385,  385,  385,  386,  388,  386,  386,  383,  381,  389,
      387,  384,  387,  387,  387,  387,  385,  382,  390,  388,
      369,  386,  388,  388,  388,  388,  383,  383,  383,  391,
      387,  387,  384,  385,  385,  385,  392,  388,  388,  386,
      387,  387,  387,  388,  388,  388,    0,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357

    } ;

static const flex_int16_t yy_nxt[1247] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       30,   29,   29,   31,    4,   32,   33,   29,   34,   35,
       36,   37,   38,   29,   39,   29,   29,   29,   29,   40,
       41,   29,   29,   42,   43,   29,   44,   45,   46,   47,
       49,   52,   49,   49,   53,   59,   50,   49,   62,   57,
       58,   49,  314,   65,   49,   48,   54,   66,   82,   49,
       60,   49,   68,   63,   49,   87,   99,   67,  100,   56,
       69,   70,   83,   55,   71,   49,   72,   72,   73,   95,

       64,  101,   49,   74,   96,   84,  102,   85,   86,   75,
       76,   49,   77,   77,   91,   73,   49,  357,   92,  115,
       74,   78,   88,   89,   79,   79,   80,   49,   49,   49,
      109,   49,   54,   93,  107,   78,   49,  136,   52,  357,
       79,   53,   52,  306,  116,   53,   79,   76,   49,   81,
       81,  161,  111,   54,   63,  127,   62,  112,   78,  110,
      128,   79,   79,  114,  119,   49,  113,   49,  108,  123,
       55,   63,   78,  137,   55,  294,  133,   79,  133,  202,
       49,  134,  134,   79,   49,   90,   90,  127,   64,   49,
      134,  134,  128,   90,   90,   90,   90,   90,   90,   90,

      192,  193,   49,   49,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   62,   49,   72,   72,  286,  109,  123,
      114,  214,   49,  117,  120,  121,  291,  121,  118,  124,
      126,   49,  129,  129,  125,   79,   79,   52,  120,  121,
       53,  130,  131,  121,  131,   64,  215,  110,   49,  216,
       48,   79,   54,  357,  228,  130,  131,   79,   62,  229,
      131,   76,   49,   77,   77,   48,  175,  357,  208,   55,
      123,  217,   78,   63,  151,  132,  132,  152,   52,  287,
      124,  157,  222,  258,  153,  125,   78,   73,  158,  154,

       64,  132,   74,  159,   49,  174,  174,  132,   49,  135,
      135,   49,  187,  187,  123,  201,  155,  135,  135,  135,
      160,  173,  202,  173,  216,   49,  174,  174,  135,  135,
      135,  135,  135,  135,   76,   49,   81,   81,  189,  189,
      163,  285,  123,   49,  203,   78,   62,  164,   79,   79,
      165,  115,  176,  169,  189,  166,  170,  177,  123,   78,
      189,  171,  127,  275,   79,  123,  280,  128,  178,  274,
       79,  215,  167,  179,  259,  182,  116,  273,  172,  260,
      183,   49,  129,  129,  186,   49,  186,  272,   49,  187,
      187,  184,  185,  123,  185,  175,  217,  175,  132,  132,

       49,  134,  134,  124,  292,  184,  185,  123,  125,  151,
      185,  188,  152,  188,  132,  175,  293,  153,  151,  153,
      132,  152,  154,   52,  154,  188,  157,  151,  204,  188,
      152,  246,  245,  205,  123,  228,  151,  206,  208,  210,
      357,  155,  207,  123,  124,  244,  211,  127,  243,  125,
      155,  212,  128,  165,   52,  160,  163,  157,  166,  155,
      163,  242,  241,  164,  158,  240,  165,  164,  213,  159,
      218,  166,  163,  295,   62,  219,   49,  238,  238,  164,
      296,  169,  220,  163,   62,  239,  160,  221,  167,  222,
      224,  169,  167,  225,  170,  123,  295,  231,  226,  171,

       49,  174,  174,  296,  167,  176,  172,  124,  123,  123,
       49,  121,  232,  121,  292,  227,  172,  123,  233,  182,
      123,  201,   49,  234,  183,  121,  293,  235,  202,  121,
      233,   49,  236,   49,  237,  234,  237,  292,   49,  238,
      238,   49,  187,  187,  201,  151,  189,  189,  152,  293,
      203,  247,  131,  299,  131,  204,  248,  180,  300,  180,
       54,   52,  189,  200,   53,  296,  131,  199,  189,  250,
      131,  111,  251,  203,  292,  151,  112,  155,  210,  153,
      198,  297,  307,  197,  252,  254,  298,  123,   52,  151,
      255,  157,  210,   55,  322,  123,  196,  182,  158,  211,

      195,  253,  183,  159,  212,  211,  332,  213,  151,  151,
      212,  210,  210,  317,  194,  163,  123,  191,  256,  254,
      160,  213,  164,  257,  255,  218,  182,   62,  262,  163,
       63,  183,  190,  307,  114,  263,  224,  117,  165,  266,
      213,  213,  118,  264,  267,  322,  215,  167,   62,  259,
       49,  288,   49,  289,   62,  169,   49,  163,  170,   64,
      265,  227,  180,  171,  224,   49,  163,  225,  163,  123,
      290,  217,  226,  224,  175,  224,  268,  123,  266,  225,
      172,  269,  215,  267,  226,  216,  123,  124,   49,  227,
      201,   49,  125,  231,  123,  123,  178,  247,  227,  357,

      227,  179,   52,  182,  233,  235,  123,  217,  271,  234,
      180,   49,  238,  238,   49,  151,  124,  151,  152,  203,
      152,  125,  185,  123,  185,  153,  357,  206,   49,  123,
      154,  250,  207,  153,  277,   49,  185,  149,  154,  124,
      185,  211,  151,  315,  125,  210,  278,  155,  316,  155,
      151,   52,  254,  210,  157,  317,  148,  255,  123,  147,
      256,  158,  163,  279,  146,  208,  159,  145,  165,  164,
      301,  163,  165,  166,  213,  144,  143,  166,  164,  142,
      262,  220,  213,  160,  141,  295,  221,  282,  140,  163,
      225,  163,  296,  139,  167,  283,  224,  138,  224,  266,

       62,  268,   49,  167,  267,   49,  222,  169,  315,  123,
      170,   49,  284,  316,   49,  171,  123,   49,   49,  182,
      317,  227,   49,  227,  183,  151,  233,  123,  210,  123,
       49,  234,  172,  151,   49,  211,  210,  182,   49,  211,
      212,  123,  183,  254,  212,  163,   49,   49,  255,   49,
       49,  182,  224,  123,  163,  225,  183,  213,   49,  307,
      226,  224,   49,  225,  266,  213,  308,  307,  226,  267,
      288,  309,  289,  123,  308,  123,  303,  227,   49,  309,
       49,   49,   49,  304,   49,  311,  227,   49,  305,  290,
      312,  123,  123,  123,  303,  303,  303,  313,   49,   49,

      301,  304,  304,  318,   49,  106,  305,  305,  319,  123,
      123,  123,  303,  324,  105,  332,  104,  123,  103,  320,
      325,  311,  317,   98,  321,  326,  312,  327,  123,   97,
      331,  123,  328,  313,  123,  292,   94,  303,  329,  313,
      311,  334,  297,  330,  318,  312,  335,  298,  231,  293,
      313,  338,  313,  336,  123,  307,  123,  324,  304,  324,
       49,   49,  308,  339,  340,  123,  325,  309,  324,  341,
       49,  326,  123,  123,  123,  325,  324,  324,   49,   49,
      326,  299,  327,  342,  340,  231,  300,  295,  343,  341,
       49,  123,  315,  296,  313,  311,   49,  316,  315,  123,

      345,  347,  123,  316,  317,  123,  348,  346,  331,  334,
      317,   49,  349,  336,  335,  347,  123,  350,  334,  303,
      348,  336,  123,  335,  336,  303,  304,  336,   49,  357,
      336,  305,  304,  123,  357,  231,  303,  305,  352,  123,
      307,  123,  324,  320,  324,  325,  357,  308,  321,  340,
      353,  342,  309,  123,  341,  123,  322,  331,  357,  231,
      357,  123,  357,  311,  357,  329,  357,  311,  312,  334,
      330,  347,  312,  357,  355,  313,  348,  313,  123,  313,
      123,  356,  123,  336,  123,  324,  123,  324,  349,  324,
      334,  357,  325,  332,  325,  335,  340,  326,  123,  326,

      336,  341,  336,  357,  331,  357,  357,  357,  347,  357,
      357,  357,  357,  348,  334,  357,  357,  357,  357,  335,
      336,  357,  357,  357,  357,  357,  336,   51,   51,   61,
       61,   52,   52,   62,   62,  122,  122,  150,  150,  156,
      156,  162,  162,  168,  168,  123,  123,  181,  181,  151,
      151,  209,  209,  163,  163,  223,  223,  230,  230,  249,
      249,  261,  261,  270,  270,  276,  276,  281,  281,  302,
      302,  310,  310,  323,  323,  333,  333,  337,  337,  344,
      344,  351,  351,  354,  354,    3,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,

      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357
    } ;

static const flex_int16_t yy_chk[1247] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        7,    8,    9,   10,    8,   11,    7,   15,   12,   10,
       10,   23,  386,   15,   11,   12,    8,   16,   23,   26,
       11,   16,   18,   12,   18,   26,   38,   16,   38,    9,
       18,   18,   25,    8,   19,   19,   19,   19,   20,   35,

       12,   39,   25,   20,   35,   25,   39,   25,   25,   20,
       21,   21,   21,   21,   30,   49,   27,   55,   30,   62,
       49,   21,   27,   27,   21,   21,   21,   33,   45,  113,
       52,   85,   55,   33,   45,   21,   56,   85,   51,   64,
       21,   51,   54,  384,   62,   54,   21,   22,   22,   22,
       22,  113,   54,   51,   64,   74,   61,   54,   22,   52,
       74,   22,   22,   61,   71,   71,   56,   89,   45,  203,
       51,   61,   22,   89,   54,  382,   78,   22,   78,  203,
       78,   78,   78,   22,   29,   29,   29,  128,   61,  133,
      133,  133,  128,   29,   29,   29,   29,   29,   29,   29,

      140,  140,  161,  280,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   63,   72,   72,   72,  280,  248,   73,
       63,  161,   79,   63,   72,   72,  381,   72,   63,   73,
      364,   76,   76,   76,   73,   79,   79,   91,   72,   72,
       91,   76,   76,   72,   76,   63,  163,  248,  214,  163,
      358,   79,   91,  160,  175,   76,   76,   79,   92,  175,
       76,   77,   77,   77,   77,   92,  331,  172,  160,   91,
      122,  163,   77,   92,  111,   77,   77,  111,  112,  285,
      122,  112,  172,  214,  111,  122,   77,  177,  112,  111,

       92,   77,  177,  112,  173,  173,  173,   77,   80,   80,
       80,  186,  186,  186,  217,  151,  111,   80,   80,   80,
      112,  120,  151,  120,  217,  120,  120,  120,   80,   80,
       80,   80,   80,   80,   81,   81,   81,   81,  135,  135,
      117,  272,  124,  258,  151,   81,  118,  117,   81,   81,
      117,  260,  124,  118,  135,  117,  118,  124,  125,   81,
      135,  118,  180,  245,   81,  127,  258,  180,  125,  244,
       81,  216,  117,  125,  216,  127,  260,  242,  118,  216,
      127,  129,  129,  129,  130,  132,  130,  241,  130,  130,
      130,  129,  129,  152,  129,  231,  216,  215,  132,  132,

      134,  134,  134,  152,  289,  129,  129,  155,  152,  150,
      129,  134,  150,  134,  132,  201,  289,  155,  153,  150,
      132,  153,  155,  156,  150,  134,  156,  154,  153,  134,
      154,  200,  198,  153,  164,  228,  158,  154,  156,  158,
      228,  150,  154,  167,  164,  197,  158,  236,  196,  164,
      153,  158,  236,  167,  159,  156,  162,  159,  167,  154,
      165,  194,  193,  162,  159,  192,  162,  165,  158,  159,
      165,  162,  166,  290,  168,  165,  237,  237,  237,  166,
      290,  168,  166,  170,  171,  190,  159,  166,  162,  168,
      170,  171,  165,  170,  171,  176,  294,  178,  170,  171,

      174,  174,  174,  294,  166,  176,  168,  178,  179,  181,
      176,  174,  178,  174,  291,  170,  171,  182,  179,  181,
      183,  250,  188,  179,  181,  174,  291,  182,  250,  174,
      183,  185,  182,  189,  184,  183,  184,  292,  184,  184,
      184,  187,  187,  187,  202,  204,  189,  189,  204,  292,
      250,  202,  187,  295,  187,  204,  202,  169,  295,  157,
      204,  205,  189,  149,  205,  295,  187,  148,  189,  206,
      187,  205,  206,  202,  293,  207,  205,  204,  207,  206,
      147,  293,  306,  146,  206,  207,  293,  210,  208,  209,
      207,  208,  209,  205,  306,  213,  143,  210,  208,  209,

      142,  206,  210,  208,  209,  213,  314,  207,  211,  212,
      213,  211,  212,  314,  141,  218,  224,  139,  211,  212,
      208,  209,  218,  211,  212,  218,  224,  219,  220,  221,
      218,  224,  138,  307,  219,  220,  221,  219,  220,  221,
      211,  212,  219,  220,  221,  307,  259,  218,  222,  259,
      137,  286,  136,  286,  259,  222,  131,  223,  222,  219,
      220,  221,  126,  222,  223,  286,  225,  223,  226,  227,
      286,  259,  223,  225,  123,  226,  225,  230,  226,  227,
      222,  225,  262,  226,  227,  262,  232,  230,  121,  223,
      247,  119,  230,  233,  234,  235,  232,  247,  225,  116,

      226,  232,  247,  233,  234,  235,  251,  262,  233,  234,
      235,  238,  238,  238,  114,  249,  251,  252,  249,  247,
      252,  251,  238,  253,  238,  249,  110,  252,  108,  263,
      249,  254,  252,  253,  254,  107,  238,  106,  253,  263,
      238,  254,  255,  300,  263,  255,  254,  249,  300,  252,
      256,  257,  255,  256,  257,  300,  105,  255,  265,  104,
      256,  257,  261,  254,  103,  256,  257,  102,  265,  261,
      296,  264,  261,  265,  255,  100,   99,  261,  264,   98,
      266,  264,  256,  257,   97,  296,  264,  266,   96,  267,
      266,  268,  296,   95,  261,  266,  267,   94,  268,  267,

      269,  268,   93,  264,  267,   88,  268,  269,  316,  270,
      269,   87,  266,  316,   86,  269,  271,   84,   83,  270,
      316,  267,   82,  268,  270,  276,  271,  277,  276,  279,
       75,  271,  269,  278,   70,  276,  278,  277,   69,  279,
      276,  282,  277,  278,  279,  281,   68,   67,  278,   66,
       65,  282,  281,  284,  283,  281,  282,  276,   60,  298,
      281,  283,   59,  284,  283,  278,  298,  309,  284,  283,
      288,  298,  288,  297,  309,  299,  297,  281,   58,  309,
       57,   53,   50,  297,  288,  299,  283,   48,  297,  288,
      299,  302,  303,  304,  302,  303,  304,  299,   47,   46,

      317,  302,  303,  304,   44,   43,  302,  303,  304,  305,
      308,  310,  305,  308,   42,  317,   41,  311,   40,  305,
      308,  310,  317,   37,  305,  308,  310,  311,  312,   36,
      313,  315,  311,  310,  318,  319,   34,  318,  312,  311,
      313,  315,  319,  312,  318,  313,  315,  319,  320,  318,
      312,  320,  313,  315,  321,  322,  323,  321,  320,  323,
       32,   31,  322,  320,  321,  324,  323,  322,  324,  321,
       28,  323,  327,  325,  326,  324,  325,  326,   24,   17,
      324,  328,  327,  325,  326,  329,  328,  327,  325,  326,
       14,  330,  332,  328,  327,  329,   13,  332,  350,  333,

      329,  330,  334,  350,  332,  335,  330,  329,  336,  333,
      350,    5,  334,  330,  333,  335,  337,  334,  336,  337,
      335,  333,  338,  336,  334,  338,  337,  335,    4,    3,
      336,  337,  338,  339,    0,  340,  339,  338,  340,  341,
      343,  342,  341,  339,  342,  340,    0,  343,  339,  341,
      340,  342,  343,  344,  341,  345,  342,  346,    0,  347,
        0,  348,    0,  344,    0,  345,    0,  346,  344,  347,
      345,  348,  346,    0,  347,  344,  348,  345,  349,  346,
      354,  347,  351,  348,  352,  351,  353,  352,  349,  353,
      354,    0,  351,  349,  352,  354,  353,  351,  355,  352,

      349,  353,  354,    0,  356,    0,    0,    0,  355,    0,
        0,    0,    0,  355,  356,    0,    0,    0,    0,  356,
      355,    0,    0,    0,    0,    0,  356,  359,  359,  360,
      360,  361,  361,  362,  362,  363,  363,  365,  365,  366,
      366,  367,  367,  368,  368,  369,  369,  370,  370,  371,
      371,  372,  372,  373,  373,  374,  374,  375,  375,  376,
      376,  377,  377,  378,  378,  379,  379,  380,  380,  383,
      383,  385,  385,  387,  387,  388,  388,  389,  389,  390,
      390,  391,  391,  392,  392,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,

      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[78] =
    {   0,
0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ansi.l"
#line 10 "ansi.l"



#include <stdio.h>
#include "y.tab.h"
void yyerror(const char* error_msg);

void printcode();
#line 878 "lex.yy.c"
#line 879 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 20 "ansi.l"

#line 1098 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 358 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1186 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "ansi.l"
{;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 22 "ansi.l"
{;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 23 "ansi.l"
{printf("%s\n", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "ansi.l"
{printf("%s\n", yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "ansi.l"
{ printcode(); return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "ansi.l"
{ printcode(); return(CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "ansi.l"
{ printcode(); return(CONST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "ansi.l"
{ printcode(); return(CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "ansi.l"
{ printcode(); return(DO); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "ansi.l"
{ printcode(); return(DOUBLE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "ansi.l"
{ printcode(); return(ELSE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "ansi.l"
{ printcode(); return(FLOAT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "ansi.l"
{ printcode(); return(FOR); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 36 "ansi.l"
{ printcode(); return(IF); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 37 "ansi.l"
{ printcode(); return(INT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 38 "ansi.l"
{ printcode(); return(RETURN); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 39 "ansi.l"
{ printcode(); return(SIZEOF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 40 "ansi.l"
{ printcode(); return(VOID); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 41 "ansi.l"
{ printcode(); return(WHILE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 43 "ansi.l"
{ printcode(); return(check_type()); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 45 "ansi.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 46 "ansi.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 47 "ansi.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 48 "ansi.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "ansi.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 51 "ansi.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 52 "ansi.l"
{ printcode(); return(CONSTANT); }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 54 "ansi.l"
{ printcode(); return(STRING_LITERAL); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "ansi.l"
{ printcode(); return(ELLIPSIS); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "ansi.l"
{ printcode(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "ansi.l"
{ printcode(); return(LEFT_ASSIGN); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "ansi.l"
{ printcode(); return(ADD_ASSIGN); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "ansi.l"
{ printcode(); return(SUB_ASSIGN); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "ansi.l"
{ printcode(); return(MUL_ASSIGN); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "ansi.l"
{ printcode(); return(DIV_ASSIGN); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "ansi.l"
{ printcode(); return(MOD_ASSIGN); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "ansi.l"
{ printcode(); return(AND_ASSIGN); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 65 "ansi.l"
{ printcode(); return(XOR_ASSIGN); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 66 "ansi.l"
{ printcode(); return(OR_ASSIGN); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 67 "ansi.l"
{ printcode(); return(RIGHT_OP); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "ansi.l"
{ printcode(); return(LEFT_OP); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "ansi.l"
{ printcode(); return(INC_OP); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 70 "ansi.l"
{ printcode(); return(DEC_OP); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 71 "ansi.l"
{ printcode(); return(PTR_OP); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "ansi.l"
{ printcode(); return(AND_OP); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "ansi.l"
{ printcode(); return(OR_OP); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "ansi.l"
{ printcode(); return(LE_OP); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 75 "ansi.l"
{ printcode(); return(GE_OP); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 76 "ansi.l"
{ printcode(); return(EQ_OP); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "ansi.l"
{ printcode(); return(NE_OP); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 78 "ansi.l"
{ printcode(); return(';'); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 79 "ansi.l"
{ printcode(); return('{'); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 80 "ansi.l"
{ printcode(); return('}'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 81 "ansi.l"
{ printcode(); return(','); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "ansi.l"
{ printcode(); return(':'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 83 "ansi.l"
{ printcode(); return('='); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 84 "ansi.l"
{ printcode(); return('('); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 "ansi.l"
{ printcode(); return(')'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 86 "ansi.l"
{ printcode(); return('['); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 87 "ansi.l"
{ printcode(); return(']'); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 88 "ansi.l"
{ printcode(); return('.'); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 "ansi.l"
{ printcode(); return('&'); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "ansi.l"
{ printcode(); return('!'); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 "ansi.l"
{ printcode(); return('~'); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 92 "ansi.l"
{ printcode(); return('-'); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 93 "ansi.l"
{ printcode(); return('+'); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 94 "ansi.l"
{ printcode(); return('*'); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 95 "ansi.l"
{ printcode(); return('/'); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 96 "ansi.l"
{ printcode(); return('%'); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 97 "ansi.l"
{ printcode(); return('<'); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 98 "ansi.l"
{ printcode(); return('>'); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 99 "ansi.l"
{ printcode(); return('^'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 100 "ansi.l"
{ printcode(); return('|'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 101 "ansi.l"
{ printcode(); return('?'); }
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 103 "ansi.l"
{ printcode(); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 104 "ansi.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 106 "ansi.l"
ECHO;
	YY_BREAK
#line 1555 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 358 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 358 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 357);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 106 "ansi.l"


yywrap()
{
	return(1);
}




int column = 0;

void printcode()
{
	ECHO;
}


int check_type()
{
/*
* pseudo code --- this is what it should check
*
*	if (yytext == type_name)
*		return(TYPE_NAME);
*
*	return(IDENTIFIER);
*/

/*
*	it actually will only return IDENTIFIER
*/

	return(IDENTIFIER);
}

